[package]
name = "futils"
version = "0.0.1"
edition = "2021"
description = "just my file util"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
